### ISSUE TITLE
ESP8266 version?

### ISSUE THREAD

**Issue by Kabron287** [tobozo/M5Stack-SD-Updater#1]
Hello, 
great achievement!
Could it be implemented for ESP8266 also?

**Comment by tobozo** [comment]
thanks!

ESP8266 has a much lower binary size limit so chances are it'll fail in many situations, also this project has many dependencies on the M5Stack Core and I'm not sure it's worth porting all that.

An easier path would be to use a [custom bootloader](https://github.com/raburton/rboot) instead.

**Comment by Kabron287** [comment]
Thanks a lot for answer. Custom bootloader is rather interesting.
