### ISSUE TITLE
Provide ready to flash .bin files in github releases page

### ISSUE THREAD

**Issue by tbaumann** [tobozo/M5Stack-SD-Updater#144]
The README suggests to use M5Burner for ease of use.

However this only runs on Windows and MacOS. It would be useful if new users who just want to bootstrap a M5Stack with SD-Boot support could fetch a recompiled .bin file from the githup page and flash it with esptool.

**Comment by tobozo** [comment]
M5Burner has a linux version

![image](https://user-images.githubusercontent.com/1893754/94191437-cb30ed00-fead-11ea-864e-7293f37256db.png)

https://m5stack.com/pages/download

Also there's already a downloadable zip with the precompiled menu.bin in the releases page (Yolo edition)

**Comment by tbaumann** [comment]
Thanks. I made wrong assumptions.
