### ISSUE TITLE
error:'class UpdateClass' has no member named 'onProgress'

### ISSUE THREAD

**Issue by dtomyy** [tobozo/M5Stack-SD-Updater#15]
Error compiling msg:
....\Documents\Arduino\libraries\M5Stack_SD_Updater\src\M5StackUpdater.cpp: In member function 'void SDUpdater::performUpdate(Stream&, size_t, String)':
....\Documents\Arduino\libraries\M5Stack_SD_Updater\src\M5StackUpdater.cpp:56:11: error: 'class UpdateClass' has no member named 'onProgress'

    Update.onProgress(M5SDMenuProgress);

How to fix it please?

**Comment by dtomyy** [comment]
Yes, Sure  selected M5Stack-Core-ESP32 and I have upload all M5Stack Advanced/Basics/Games sample and M5StackSAM's ExampleMENU also no problem.

**Comment by tobozo** [comment]
Hard to say with just two lines of errors, can you check "show verbose output during compilation" and sure the compiler warnings are set to none in the preferences ?

Also can you please try to run this sketch and paste the result:

```
void setup() {
 
  Serial.begin(115200);
 
  Serial.println("Using ESP object:");
  Serial.println(ESP.getSdkVersion());
 
  Serial.println("Using lower level function:");
  Serial.println(esp_get_idf_version());
}
 
void loop() {}
```

**Comment by dtomyy** [comment]
Thanks for you help :)
![image](https://user-images.githubusercontent.com/5944461/40281197-d3aad9b2-5c90-11e8-9213-76cff1fa40d6.png)

**Comment by tobozo** [comment]
lol you're meant to flash your M5Stack with this sketch and capture the serial console output

You can open the serial console by clicking on the looking glass icon in the upper right corner.
Do that, then flash the M5 with the sketch.

**Comment by dtomyy** [comment]
I don't know why, but I comment the error line:
![image](https://user-images.githubusercontent.com/5944461/40281515-984e77a2-5c95-11e8-9936-1b875e6ac92b.png)

And I can done compiling.
![image](https://user-images.githubusercontent.com/5944461/40281538-d99c7ba0-5c95-11e8-90b5-ec0335bb4059.png)

**Comment by tobozo** [comment]
I had to comment this function too for the ESP8266 version, but you'll lose the loader by doing that.

My sdk version:
```
Using ESP object:
v3.1-dev-661-gf586f5e6
Using lower level function:
v3.1-dev-661-gf586f5e6
```

You should update your ESP32 SDK, you're one minor version behind :-)

**Comment by dtomyy** [comment]
I don't know what do you mean "lose the loader"
![image](https://user-images.githubusercontent.com/5944461/40282101-7d91572a-5c9c-11e8-950f-dedcede5fa25.png)

Can I change applications order?
![image](https://user-images.githubusercontent.com/5944461/40282102-82e1717e-5c9c-11e8-8e02-c4b3a920f2c5.png)

**Comment by dtomyy** [comment]
I'm not developer, Image is crop from https://github.com/hkoffer/M5Stack-Thermal-Camera-

![thermal_cam_interpolate](https://user-images.githubusercontent.com/5944461/40282346-a3d16d54-5ca0-11e8-9a86-ea3cb6d9dde1.jpg)

thermal_cam_interpolate.json
`{"width":110,"height":110, "authorName":"Offer DIYER", "projectURL": "https://t.co/qxFj4EpW9n","credits":"https://twitter.com/Offer68328171/status/990110652671799297"} 
`

**Comment by artkeller** [comment]
I'll get the same compilation error:

> C:\Users\artkeller\Documents\Arduino\libraries\M5Stack-SD-Updater\src\M5StackUpdater.cpp: In member function 'void SDUpdater::performUpdate(Stream&, size_t, String)':

> C:\Users\artkeller\Documents\Arduino\libraries\M5Stack-SD-Updater\src\M5StackUpdater.cpp:67:11:
 error: 'class UpdateClass' has no member named 'onProgress'

    Update.onProgress(M5SDMenuProgress);

           ^

The development environment is set as follows:

> ets Jun  8 2016 00:22:57
rst:0x1 (POWERON_RESET),boot:0x17 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0018,len:4
load:0x3fff001c,len:956
load:0x40078000,len:0
load:0x40078000,len:11904
entry 0x40078a3c
Using ESP object:
v3.0-dev-1024-g92748142
Using lower level function:
v3.0-dev-1024-g92748142

Trying to "comment the reported line of code" compiles the sketch but the uploaded SPIFFS will not be used...

> rst:0xc (SW_CPU_RESET),boot:0x17 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0018,len:4
load:0x3fff001c,len:956
load:0x40078000,len:0
load:0x40078000,len:11904
entry 0x40078a3c
initializing...OK
Scanning SPIFFS for binaries

> No binary to transfer
Listing directory: /
  DIR : /data
  DIR : /jpg
  DIR : /json
  DIR : /mod
  DIR : /mp3

> Guru Meditation Error of type LoadProhibited occurred on core  1. Exception was unhandled.
Register dump:
PC      : 0x400014fd  PS      : 0x00060d30  A0      : 0x800d36d3  A1      : 0x3ffe2190  
A2      : 0x00000000  A3      : 0xfffffffc  A4      : 0x000000ff  A5      : 0x0000ff00  
A6      : 0x00ff0000  A7      : 0xff000000  A8      : 0x00000000  A9      : 0x3ffe21d0  
A10     : 0x3ffcb128  A11     : 0x3ffcc818  A12     : 0x0000000f  A13     : 0x3ffdbc9e  
A14     : 0x00000000  A15     : 0x00000000  SAR     : 0x00000018  EXCCAUSE: 0x0000001c  
EXCVADDR: 0x00000000  LBEG    : 0x400014fd  LEND    : 0x4000150d  LCOUNT  : 0xffffffff  

> Backtrace: 0x400014fd:0x3ffe2190 0x400d36d0:0x3ffe21a0 0x400d37a0:0x3ffe21d0 0x400f9ade:0x3ffe2250 0x400d25c9:0x3ffe2270 0x400d28ed:0x3ffe22e0 0x400d2da7:0x3ffe2370 0x400f814b:0x3ffe23e0

> Rebooting...

The ESP32 Exception Decoder reports

> Decoding 11 results
0x400d36d0: ILI9341::drawChar(int, int, unsigned char, unsigned int, unsigned int, unsigned char) at C:\Users\artkeller\Documents\Arduino\libraries\M5Stack\src\utility/Display.cpp line 1272
0x400d37a0: ILI9341::spi_end() at C:\Users\artkeller\Documents\Arduino\libraries\M5Stack\src\utility/Display.cpp line 1272
:  (inlined by) ILI9341::drawChar(int, int, unsigned char, unsigned int, unsigned int, unsigned char) at C:\Users\artkeller\Documents\Arduino\libraries\M5Stack\src\utility/Display.cpp line 1449
0x400f9ade: nd6_send_rs at /Users/ficeto/Desktop/ESP32/ESP32/esp-idf-public/components/lwip/core/ipv6/nd6.c line 647
0x400d25c9: setup() at C:\Users\artkeller\Documents\Arduino\libraries\M5StackSAM-master\examples\ExampleMENU/ExampleMENU.ino line 56
0x400d28ed: LoRaClass::LoRaClass() at C:\Users\artkeller\Documents\Arduino\libraries\M5Stack\src/M5LoRa.cpp line 502
0x400d2da7: ILI9341::writecommand(unsigned char) at C:\Users\artkeller\Documents\Arduino\libraries\M5Stack\src\utility/Display.cpp line 1272
0x400f814b: ip6_input at /Users/ficeto/Desktop/ESP32/ESP32/esp-idf-public/components/lwip/core/ipv6/ip6.c line 955

I don't understand what's wrong.

Can you please document how to run the M5Stack SD updater step by step, including uploading /data content, etc.? For me it becomes more and more of a secret... I thought I understood the system - currently I doubt myself.

Many thanks.

**Comment by tobozo** [comment]
@dtomyy you can change the order of the applications by renaming them.

The list is sorted but it's not using natural sorting so it's A-Z then a-z, and it's only scanning the 3 first chars.

If you need to improve the sorting algo [it's here](https://github.com/tobozo/M5Stack-SD-Updater/blob/master/examples/M5Stack-SD-Menu/M5Stack-SD-Menu.ino#L383)

happy hacking ^_^

**Comment by tobozo** [comment]
closing this issue as solved, feel free to reopen if something new comes up
