### ISSUE TITLE
M5Stack.h and SdFat.h combination causes compile error 

### ISSUE THREAD

**Issue by GOB52** [tobozo/M5Stack-SD-Updater#180]
* Using master 1.2.4
* iMac macOS 10.15.7 (Catalina)
* VsCode 1.77.3
* PlatformIO Core, version 6.1.6
---

The combination of M5Unified and SdFat is not a problem though, M5Stack and SdFat combination causes compile error.

```cpp
#include <M5Stack.h>
#include <LovyanGFX.h>
LGFX lcd;
# define SDU_NO_AUTODETECT
# define USE_SDFATFS
# define HAS_M5_API
# define SDU_USE_DISPLAY
# define HAS_LGFX
# define SDU_Sprite LGFX_Sprite
# define SDU_DISPLAY_TYPE LGFX*
# define SDU_DISPLAY_OBJ_PTR &lcd
# include <M5StackUpdater.h>
```

```
.pio/libdeps/release_SDU/M5Stack-SD-Updater/src/M5StackUpdater.hpp:541:13: error: 'SDU_SdFatFsPtr' was not declared in this scope
         if( SDU_SdFatFsPtr ) {
// and more errors.
```

The reason seems to be that \_\_SD_H\_\_ is enabled because M5Stack.h depends on SD.h.
("#if !SDU_HAS_FS" in M5StackUpdater.hpp does not enable and SdFat-related includes are not performed)

```cpp
// In this combination, 
// SDU_HAS_FS is not zero, so not going through SdFat related parts.
#if ! SDU_HAS_FS  
  #define SDU_HAS_SD 
  #if defined USE_SDFATFS
    #pragma message "SDUpdater will use SdFat" 
    #undef __has_include
    #include <misc/sdfat32fs_wrapper.h>
```

Sorry if this is an unsupported combination.

**Comment by tobozo** [comment]
CI tests didn't yield any error, however I spotted a nasty bug with `SDUCfg.setBinFileName()` and will produce a new release and close the associated issues.
