### ISSUE TITLE
Compile error of %s augument

### ISSUE THREAD

**Issue by tomorrow56** [tobozo/M5Stack-SD-Updater#32]
Hello,

When I compile version 0.4.1 with AuruinoIDE, get the following error.

Arduino\libraries\M5Stack-SD-Updater\src\M5StackUpdater.cpp:212:91: error: format '%s' expects argument of type 'char*', but argument 3 has type 'const __FlashStringHelper*' [-Werror=format=]

     Serial.printf( "[M5Stack-SD-Updater] SD Updater version: %s\n", M5_SD_UPDATER_VERSION );

 Casting to .char * will eliminate the error. Is this correct?
    Serial.printf( "[M5Stack-SD-Updater] SD Updater version: %s\n", (char*)M5_SD_UPDATER_VERSION );

Thank you.

**Comment by tobozo** [comment]
Hello, thank you for reporting this.

Apparently this only occurs when "all" is selected in Arduino compilation warning preferences.

![image](https://user-images.githubusercontent.com/1893754/54737309-930d6780-4baf-11e9-91ce-00302ae77cb9.png)

I've applied your suggested fix for `M5_SD_UPDATER_VERSION` and also for `M5_LIB_VERSION`.

Thanks a lot for your contribution 🙇 👍

**Comment by tomorrow56** [comment]
Thank you very much!!
